# --- Linux ---
- name: Download SSM Agent RPM
  get_url:
    url: "https://amazon-ssm-agent.s3.us-east-1.amazonaws.com/latest/linux_amd64/amazon-ssm-agent.rpm"
    dest: "/tmp/amazon-ssm-agent.rpm"

- name: Install SSM Agent RPM
  yum:
    name: /tmp/amazon-ssm-agent.rpm
    state: present

- name: Enable and start SSM Agent
  service:
    name: amazon-ssm-agent
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Install SSM Agent (Debian/Ubuntu)
  apt:
    name: amazon-ssm-agent
    state: latest
  when: ansible_os_family == "Debian"

- name: Enable and start SSM Agent (Linux)
  service:
    name: amazon-ssm-agent
    state: started
    enabled: yes
  when: ansible_os_family in ["RedHat", "Debian"]

# --- Windows ---
- name: Download SSM Agent MSI
  win_get_url:
    url: https://s3.amazonaws.com/amazon-ssm-agent/latest/windows_amd64/AmazonSSMAgentSetup.msi
    dest: C:\Temp\AmazonSSMAgentSetup.msi
  when: ansible_os_family == "Windows"

- name: Install SSM Agent (Windows)
  win_package:
    path: C:\Temp\AmazonSSMAgentSetup.msi
    state: present
  when: ansible_os_family == "Windows"

- name: Ensure SSM Agent service is running (Windows)
  win_service:
    name: AmazonSSMAgent
    start_mode: auto
    state: started
  when: ansible_os_family == "Windows"